In [1]:
cd /Users/karolinegriesbach/Documents/Innkeepr/Git/evaluation-and-execution-scripts/

/Users/karolinegriesbach/Documents/Innkeepr/Git/evaluation-and-execution-scripts

/Users/karolinegriesbach/Documents/Innkeepr/Git/evaluation-and-execution-scripts/.venv/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [2]:
import logging
import pandas as pd
import delta_sharing
from datetime import timezone

import general_functions.databricks_client as db_client
from general_functions.return_workspace_ids import return_workspace_ids
from general_functions.constants import return_api_url
from general_functions.call_api_with_account_id import send_to_innkeepr_api_paginated

In [3]:
def timestamp_milliseconds(date):
    """
    Function to transform datesting in
    timestamp with milliseconds
    Args:
        date: date string
    """
    date = pd.to_datetime(date).replace(tzinfo=timezone.utc).timestamp() * 1000
    date = int(date)
    return date

In [4]:
customer = "MissPompadour GmbH" #6617da9c01c2ab3bd12c63cb
date = "2026-07-19"#T15:00:00.000Z"
end_date = "2026-07-20"#T20:00:00.000Z"
use_session_id = True
url_tracking_param = "gclid"
url_campaign_param = "gad_campaignid"# klar_cpid"
url = return_api_url()
print(f"url = {url}")
account_id = return_workspace_ids()
account_id = [acc["id"] for acc in account_id if acc["name"] == customer]
account_id = account_id[0]

url = https://targeting.innkeepr.ai/
https://targeting.innkeepr.ai/api/core/workspaces/query

In [5]:
if use_session_id:
    profile_path = db_client.return_databricks_client()
    table_path = f"{profile_path}#delta_share_events.{account_id}.features_view_30_outlook"
    df = delta_sharing.load_as_pandas(table_path, limit=500000)
    #print(df["created"].min(), df["created"].max())
    #df = df[df["created"].astype("string")>=date]
    df = df[df["treatment"].isnull()]
    print(df["created"].min(), df["created"].max())
    session_ids=df["session"].unique().tolist()
    print(f"len session_ids = {len(session_ids)}")
    content = {"sessionId":session_ids[0:10]}
else:
    date_format_dash = "%Y-%m-%d"
    content = {
            "created": {
                "$gte":  pd.to_datetime(date).strftime(date_format_dash),
                "$lte": pd.to_datetime(end_date).strftime(date_format_dash),
            }
        }
    print(content)

2026-06-20 00:07:06.949000 2026-07-19 23:26:12.578000
len session_ids = 184270

In [8]:
content = {"sessionId":session_ids[0:50000]}

In [9]:
sessions_response = send_to_innkeepr_api_paginated( 
    f"{url}api/sessions/query",
    account_id,
    content,
    logging
)

In [10]:
sessions = pd.json_normalize(sessions_response)
sessions

,id,sessionId,anonymousId,profileId,created,expirationDate,referrer,activeIntegrations,campaign.gclid,campaign.gad_campaignid,campaign.klar_adid,campaign.klar_cpid
0,6a4bcceb87320b852b3806ad,0002020e-f9c6-4da5-8a2d-ba48d416d9c6,6a4a50525b03fa99d9013d62,None,2026-07-06T15:42:34.108Z,2026-07-06T16:12:32.599Z,https://www.google.com/,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",CjwKCAjwpK3SBhASEiwAtV1SPJBLfAU1zwn9eHP_igb9p-...,NaN,NaN,NaN
1,6a3be38a87320bbf3c2897dd,00027eae-8f60-49cd-989a-7c1c1f152ed5,6a33c5501e0c3e395e18c748,None,2026-06-24T14:02:44.651Z,2026-06-24T14:32:42.681Z,https://www.google.com/,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",NaN,NaN,NaN,NaN
2,6a4d4eb687320b4e6430af25,00036d0a-dca1-4d43-83b3-05bd07fcd658,6a4d4eb05b03fa99d9bb0572,None,2026-07-07T19:08:32.028Z,2026-07-07T19:38:31.787Z,https://www.pinterest.com/,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",NaN,NaN,NaN,NaN
3,6a47ad9d87320be381439212,000434f9-5888-4eb7-801d-a06aba79e07e,6a47ad8e1f1668864bc48a37,None,2026-07-03T12:39:48.110Z,2026-07-03T13:09:47.810Z,https://suche.t-online.de/,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",NaN,NaN,NaN,NaN
4,6a4e4a7e87320ba2f1475a5a,00049000-3735-455b-9737-3135f258adca,6a4e4a638b3b5b6eee583500,None,2026-07-08T13:02:27.824Z,2026-07-08T13:32:26.992Z,https://www.misspompadour.de/c/misspompadour-d...,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
49868,6a4c300387320bc4061ca2e3,fff6b0c7-27c9-4110-8f63-6808a0c0efa1,6a4c2fce5b03fa99d97b651b,None,2026-07-06T22:44:30.479Z,2026-07-06T23:14:29.994Z,https://www.misspompadour.de/p/misspompadour-b...,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",NaN,NaN,NaN,NaN
49869,6a467fbe87320b9d3e7de500,fff78b74-0ed0-4a26-8b55-b5c804307fc3,6a467fa6b30d92c844706dec,None,2026-07-02T15:11:34.250Z,2026-07-02T15:41:33.362Z,android-app://com.google.android.googlequickse...,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",CjwKCAjwmJjSBhB-EiwAkZgxi6QcRjsMzxhac0S2HDOu7F...,NaN,NaN,NaN
49870,6a4fb2e687320b41125b1b02,fffb3941-1239-43d8-bbcc-58e22065ce9e,6a4fb2de5b03fa99d93b18fb,None,2026-07-09T14:40:30.772Z,2026-07-09T15:10:30.675Z,https://www.google.com/,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",EAIaIQobChMIvYHGy-nFlQMVpRkGAB2okwW-EAQYECABEg...,21170410955,NaN,NaN
49871,6a3831a187320bcb0320f9ad,fffc1e20-1616-46f6-95d9-6db3b1e8f2e7,6a38319a78766801a4b0ae10,None,2026-06-21T18:46:50.999Z,2026-06-21T19:16:50.689Z,https://www.google.com/,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",CjwKCAjwl97RBhBWEiwAa9rbXcvqML3aaGavifwJIXD-jE...,NaN,NaN,NaN
49872,6a4d219487320be00a37db59,fffded99-27e5-44a4-b044-e6d7eec25380,6a4d16855b03fa99d9a91ad8,None,2026-07-07T15:55:56.745Z,2026-07-07T16:25:55.466Z,,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",NaN,NaN,NaN,NaN

In [34]:
f"campaign.{url_campaign_param}", sessions[f"campaign.{url_campaign_param}"].value_counts()

('campaign.gad_campaignid',
 22745916931    1966
 23979215238    1155
 17609735727     789
 21170410955     438
 23950420534     373
                ...
 22176720170       1
 23950420471       1
 22906104400       1
 21028496283       1
 22669521049       1
 Name: campaign.gad_campaignid, Length: 94, dtype: int64)

In [12]:
cmapaign_but_no_gclid=sessions[(sessions[f"campaign.{url_tracking_param}"].isnull())&(sessions[f"campaign.{url_campaign_param}"].notnull())]
cmapaign_but_no_gclid

,id,sessionId,anonymousId,profileId,created,expirationDate,referrer,activeIntegrations,campaign.gclid,campaign.gad_campaignid,campaign.klar_adid,campaign.klar_cpid
14,6a51f05e87320b2eeb635132,0015d4ac-ce3c-4e6f-9363-7586f6fb7450,6a51f03bde432272186a9a17,None,2026-07-11T07:26:51.210Z,2026-07-11T07:56:51.040Z,,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",NaN,17238160785,NaN,NaN
66,6a4fd49487320be49d05f137,005cd173-2a30-48dc-87c1-8666e6341b45,6a4eae898b3b5b6eee75e665,None,2026-07-09T17:04:03.402Z,2026-07-09T17:34:02.137Z,,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",NaN,21025520158,NaN,NaN
202,6a576b5a87320b0f3a031a16,01136b79-e7d6-49fd-962a-1c3c1ad1520f,6a576b496c50eb6388c2ed6e,None,2026-07-15T11:13:13.494Z,2026-07-15T11:43:12.996Z,,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",NaN,23950420534,NaN,NaN
209,6a5d0d1fb8050ec6295848e2,011a602d-d358-4ee9-9c65-e903f3968733,6a5d0d09d8ca20c7da5b438c,None,2026-07-19T17:44:41.990Z,2026-07-19T18:14:41.350Z,,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",NaN,22745916931,NaN,NaN
216,6a595befb8050edd990309a4,01218d8a-d94e-4b4e-8aa1-5fc9f9942d69,6a595bd9437bcf5c629221e2,None,2026-07-16T22:31:53.696Z,2026-07-16T23:01:53.419Z,,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",NaN,17619925673,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
49453,6a5d52b2b8050e06fb49c376,fde5243d-be63-4eb8-bfc6-666e11a62c25,6a5d5264d8ca20c7da6d0d73,None,2026-07-19T22:40:36.169Z,2026-07-19T23:10:35.832Z,,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",NaN,17238160785,NaN,NaN
49580,6a532e4787320b49ef5dc384,fe7301ed-c55b-40de-946d-56b84eaf0f9e,6a532e35de43227218a2fa3c,None,2026-07-12T06:03:33.068Z,2026-07-12T06:33:31.358Z,,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",NaN,23979215238,NaN,NaN
49760,6a55cb8f87320b0f306ace73,ff7adbaf-e938-4c92-8e78-0cab5d8f5235,6a55cb56575c9b02b8e92761,None,2026-07-14T05:38:30.904Z,2026-07-14T06:08:30.694Z,,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",NaN,12270019087,NaN,NaN
49816,6a57b86a87320badf2118241,ffba619e-43d4-4d9a-86ba-b7651b6d4422,6a57b8536c50eb6388d4e08d,None,2026-07-15T16:41:55.771Z,2026-07-15T17:11:55.549Z,,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",NaN,17238160785,NaN,NaN
49867,6a593fe1b8050edd282826a2,fff6ae82-296d-4b47-b0a1-8d49ae70a1a5,6a593fce4ce2f36cf3b64470,None,2026-07-16T20:32:14.963Z,2026-07-16T21:02:14.759Z,,"[{'name': 'facebook'}, {'name': 'googleAnalyti...",NaN,6459677513,NaN,NaN

In [13]:
sessions.to_parquet(f"DataChecks/sessions/test_sessions_{customer}.parquet")

# Some Checks

## check signals

In [35]:
use_campaign_id = f"campaign.{url_campaign_param}" 
print(use_campaign_id)
signals = send_to_innkeepr_api_paginated(
    f"{url}api/ads/query",
    account_id,
    #{"externalId":["1435494216", "267300181"]},
    {"externalId": sessions[use_campaign_id].dropna().unique().tolist()},
    #{"adAccountId":"552565349"},
    logging
)

signals = pd.json_normalize(signals)
signals

campaign.gad_campaignid

Empty DataFrame
Columns: []
Index: []

In [36]:
signals["connection"].value_counts()

KeyError: 'connection'

In [27]:
signals["externalId"].value_counts()

Cj0KCQjw0JnRBhDJARIsALobnXYf6NtJoWvBlkp5zzaDpLpYFCi8bFY0DEqERQdbCphW_oBETdFvTwQaAqwBEALw_wcB    1
CjwKCAjwvNfSBhBiEiwAyaGMCe2AEK4c9jK89UFsizC5lV_oH5jTJ-t83wKGvFInK6alZVTPhuZcVxoCdpMQAvD_BwE     1
CjwKCAjwvNfSBhBiEiwAyaGMCe5O13CT5JA-61hmCvjqtGAYcRtOn7pgFIfKDpOfQBrPyq8cRQzGIhoC_UwQAvD_BwE     1
CjwKCAjwvNfSBhBiEiwAyaGMCe7PiMXcJXy2yOeNThXi6nE2Upn_lAUZruh7XEuXfkVfQaug9CEm-hoC04QQAvD_BwE     1
CjwKCAjwvNfSBhBiEiwAyaGMCeAfAsi7Pv_mCinBIVfvFDw-d_01E0PymW08HHwV1NT-Hg3FfErrhBoCWdIQAvD_BwE     1
                                                                                               ..
CjwKCAjw3ejRBhAdEiwADkqPn7XQIa27FVN8DjPjptYlEQBdrB8Oh1nQ4BEWC7knY4szcGsed9-8qxoCoqwQAvD_BwE     1
CjwKCAjw3ejRBhAdEiwADkqPn7ZBQFMUPgEbJ8y5XKT7LXFnnnAqSIrb7ZEWaH7LX1EfT5r78AhJ1RoCFhkQAvD_BwE     1
CjwKCAjw3ejRBhAdEiwADkqPn7_n5LoLaiYCix1-TfeLDT3DyPJxdVRY4iIYZJZuwHLQ9BJvM1CnNxoCteQQAvD_BwE     1
CjwKCAjw3ejRBhAdEiwADkqPn7cHYW_AMUxJR3P4Sjx9TUNpLgAkWQhq6Sa7NfGkCnPQvwfdFE8WpRoChBEQAvD_BwE     1
EAIaIQobChMIzvvlo6nelQMVE01BAh1s1gH2EAQYAiABEgK5NvD_BwE                                         1
Name: externalId, Length: 12793, dtype: int64

In [29]:
signals["relates_to.treatment"].value_counts()

69deca5b87320b6c16018439    1
69deca5a87320b6c160183cb    1
Name: relates_to.treatment, dtype: int64

In [32]:
treamtents = send_to_innkeepr_api_paginated(
    f"{url}api/treatments/query",
    account_id,
    
    {"id":signals["relates_to.treatment"].dropna().unique().tolist()},
    logging
)

treamtents = pd.json_normalize(treamtents)
treamtents

,id,externalId,connection,name,lastUpdated,created,properties.type,properties.status,properties.effectiveStatus,properties.adAccountId,properties.adAccountName,relates_to.campaign.id,relates_to.campaign.name,relates_to.campaign.resourceName,relates_to.adGroup.id,relates_to.adGroup.name,relates_to.adGroup.resourceName,relates_to.customer.resourceName,relates_to.customer.id
0,69deca5a87320b6c160183cb,157942651893,609ffc4578188e83a2bc2c2c,Abwaschbare Wandfarbe,2026-07-19T23:16:35.716Z,2026-04-14T23:14:32.500Z,SEARCH_STANDARD,active,serving,6784504455,MissPompadour,20962496787,DE_Search_Generic_Produkte|Typ,customers/6784504455/campaigns/20962496787,157942651893,Abwaschbare Wandfarbe,customers/6784504455/adGroups/157942651893,customers/6784504455,6784504455
1,69deca5b87320b6c16018439,160976321420,609ffc4578188e83a2bc2c2c,Brand Baumarkt,2026-07-19T23:16:35.712Z,2026-04-14T23:14:32.500Z,SEARCH_STANDARD,active,serving,6784504455,MissPompadour,12270019087,DE_Search_Brandkombi_MissPompadour,customers/6784504455/campaigns/12270019087,160976321420,Brand Baumarkt,customers/6784504455/adGroups/160976321420,customers/6784504455,6784504455

In [ ]:
for col in treamtents:
    for signal in ["1435494216", "267300181"]:
        temp = treamtents[treamtents[col].astype("str").str.contains(signal)]
        if len(temp)>0:
            print(col, signal, len(temp))

## check with conversions

In [ ]:
from general_functions.datetime_helper import transform_date_to_timestamp_milliseconds

test = sessions[sessions["campaign.ad_id"].isnull()==False]
meta_sessions = test["sessionId"].dropna().unique().tolist()
content = {
     "created": {
                     "$gte": transform_date_to_timestamp_milliseconds("20250818"),
                     "$lte": transform_date_to_timestamp_milliseconds("20250819"),
               }
    }
conversions = send_to_innkeepr_api_paginated(
    f"{url}/conversions/query",
    account_id,
    content,
    logging
    
)

conversions = pd.json_normalize(conversions)
conversions

In [ ]:
conversions_matches = conversions[conversions["sessionId"].isin(meta_sessions)]
conversions_matches

In [ ]:
externalIds = sessions[sessions["sessionId"].isin(conversions_matches["sessionId"])]["campaign.utm_id"].dropna().unique().tolist()
len(externalIds), externalIds

In [ ]:
signals = send_to_innkeepr_api_paginated(
    f"{url}/signals/query",
    account_id,
    {"externalId":externalIds},
    logging
)

signals = pd.json_normalize(signals)
signals

In [ ]:
treatments = send_to_innkeepr_api_paginated(
    f"{url}/treatments/query",
    account_id,
    {"id":signals["relates_to.treatment"].dropna().unique().tolist()},
    logging
)
treatments = pd.json_normalize(treatments)
treatments

# chech sessions and gclids

In [ ]:
sessions_with_conversions = pd.merge(sessions, conversions_matches, how="left", left_on="sessionId", right_on="sessionId")
sessions_with_gclid = sessions_with_conversions[sessions_with_conversions["campaign.gclid"].isnull() == False]