In [1]:
cd /Users/karolinegriesbach/Documents/Innkeepr/Git/evaluation-and-execution-scripts/

/Users/karolinegriesbach/Documents/Innkeepr/Git/evaluation-and-execution-scripts

/Users/karolinegriesbach/Documents/Innkeepr/Git/evaluation-and-execution-scripts/.venv/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [2]:
import logging
import delta_sharing
import pandas as pd

import general_functions.databricks_client as db_client
from general_functions.return_workspace_ids import return_workspace_ids
from general_functions.constants import return_api_url
from general_functions.call_api_with_account_id import call_api_with_accountId, send_to_innkeepr_api_paginated

In [3]:
profile_path = db_client.return_databricks_client()
table_path = f"{profile_path}#delta_share_events.monitoring.prefect_logs" #features_view_30_outlook"
df = delta_sharing.load_as_pandas(table_path)#, limit=200000)

In [4]:
max_date = df["timestamp"].max()
max_date

Timestamp('2026-09-15 10:28:08.159880')

In [5]:
df.to_csv(f"DataChecks/prefect_logs/prefect_logs_{max_date}_dev.csv", index=False)

In [7]:
df["date"] = pd.to_datetime(df["timestamp"]).dt.date
#temp = df[df["node_name"].isin(["x4llarge"])].sort_values(by="timestamp")
temp = df[df["timestamp"] >= "2026-09-13"].sort_values(by="timestamp")
#temp = temp[temp["timestamp"] <= "2025-09-04"].sort_values(by="timestamp")
temp

,name,timestamp,audience_id,duration,type,goal,goal_id,size,targeting_outlook,conversion_probability_cgroup,...,source,node_name,workspace_name,workspace,workspace_id,success_rate,objective,objective_id,connection,date
121610,k8-targeting,2026-09-13 00:10:16.594219,69eb91ce62dfd69717cb9a0c,120.856117,targeting,None,None,None,30,57.959999,...,None,8gib,None,Ective,6509682e62fd231df8316da5,NaN,Käufe maximieren,6a56084c4d59db27dd5979c9,googleAnalytics,2026-09-13
121611,k8-targeting,2026-09-13 00:18:18.459477,6a1efe081370504ba68c9581,421.062836,targeting,None,None,None,90,73.120003,...,None,8gib,None,MissPompadour GmbH,69c682f3f7cc7ee4f85c9aac,NaN,Käufe maximieren,6a561bd74d59db27dd5b45c0,facebook,2026-09-13
121612,k8-targeting,2026-09-13 00:21:41.066152,6a351b658c0700b3c35cd9b7,723.781616,targeting,None,None,None,60,0.000000,...,None,16gib,None,ahead-nutrition.com,69df9adc32d85c8da4a2fd4e,NaN,Käufe maximieren,6a55ece14d59db27dd56e59c,googleAnalytics,2026-09-13
121613,k8-targeting,2026-09-13 00:25:22.789530,69245bba105ef186b0db413c,360.739807,targeting,None,None,None,90,98.970001,...,None,16gib,None,Rosental,63eba9a1bfc19074666d7856,NaN,Käufe maximieren,6a4656c0f9d21ffe516157e4,facebook,2026-09-13
121614,k8-targeting,2026-09-13 00:30:30.077158,69676960a5250a665d0aaf9b,1031.244019,targeting,None,None,None,90,19.430000,...,None,32gib,None,More,68c7cbc952d0b4ef38710f7e,NaN,Käufe maximieren,6a561a144d59db27dd5b1b39,facebook,2026-09-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122096,k8-targeting,2026-09-15 10:00:41.199573,6a719abf3a366f18af8f5cc6,361.074646,targeting,None,None,None,30,77.220001,...,None,8gib,None,Rosental,63eba9a1bfc19074666d7856,NaN,Käufe maximieren,6a4656c0f9d21ffe516157e4,googleAnalytics,2026-09-15
1,k8-targeting,2026-09-15 10:01:08.982763,6a906ba36a188561250de726,120.564354,targeting,None,None,None,180,NaN,...,None,8gib,None,VITAFORM,6a2fdb12ce25063132a871c8,NaN,Käufe maximieren,6a906a856a188561250dcdcc,facebook,2026-09-15
0,k8-targeting,2026-09-15 10:06:41.480436,6a70afc03a366f18af7cf75f,3374.518799,targeting,None,None,None,180,NaN,...,None,32gib,None,ESN,68b9534c5287866a2c94a8f5,NaN,Käufe maximieren,6a561ad74d59db27dd5b2dea,facebook,2026-09-15
3,k8-targeting,2026-09-15 10:19:55.558274,68b69ffe2e5f2d9a58ce69e6,2214.875732,targeting,None,None,None,90,60.330002,...,None,64gib,None,Tchibo,6870b934768354324d58e9cf,NaN,Käufe maximieren,6a561d1eebcc88074036e58c,criteo,2026-09-15
2,k8-targeting,2026-09-15 10:28:08.159880,68b69dff2e5f2d9a58cce692,1580.487915,targeting,None,None,None,90,71.800003,...,None,64gib,None,Tchibo,6870b934768354324d58e9cf,NaN,Käufe maximieren,6a561d1eebcc88074036e58c,criteo,2026-09-15

In [12]:
temp_aud = temp[temp["audience_id"]=="68cbfa5577b55cfe740fbc8b"]
temp_aud.transpose()

,121908,122029
name,googleConversionUpdate,googleConversionUpdate
timestamp,2026-09-13 23:37:21.907529,2026-09-14 23:36:27.847402
audience_id,68cbfa5577b55cfe740fbc8b,68cbfa5577b55cfe740fbc8b
duration,360.805908,360.743286
type,ga_conversion_update,ga_conversion_update
goal,None,None
goal_id,None,None
size,None,None
targeting_outlook,None,None
conversion_probability_cgroup,NaN,NaN
conversion_probability_tgroup,NaN,NaN
f1_causal,NaN,NaN
f1_conversion,87.410004,87.410004
targeted_users,NaN,NaN
total_users_in_percentage,NaN,NaN
status,success,success
audience_type,countMax,countMax
source,None,None
node_name,8gib,8gib
workspace_name,None,None
workspace,to teach,to teach
workspace_id,6810a17e879ec174107609b1,6810a17e879ec174107609b1
success_rate,100.0,100.0
objective,Upgrades maximieren,Upgrades maximieren
objective_id,6a465589f9d21ffe5161380a,6a465589f9d21ffe5161380a
connection,googleAdwords,googleAdwords
date,2026-09-13,2026-09-14

In [10]:
temp_aud = temp[temp["audience_id"]=="6a2addee1370504ba6ff6dfe"]
temp_aud.transpose()

                                                   121637
name                                         k8-targeting
timestamp                      2026-09-13 01:09:13.357883
audience_id                      6a2addee1370504ba6ff6dfe
duration                                       421.181671
type                                            targeting
goal                                                 None
goal_id                                              None
size                                                 None
targeting_outlook                                      90
conversion_probability_cgroup                   60.009998
conversion_probability_tgroup                   88.290001
f1_causal                                             NaN
f1_conversion                                   93.669998
targeted_users                                   427903.0
total_users_in_percentage                            50.0
status                                            success
audience_type                                        seed
source                                               None
node_name                                            8gib
workspace_name                                       None
workspace                              MissPompadour GmbH
workspace_id                     69c682f3f7cc7ee4f85c9aac
success_rate                                          NaN
objective                                Käufe maximieren
objective_id                     6a561bd74d59db27dd5b45c0
connection                                googleAnalytics
date                                           2026-09-13

In [11]:
sys.exit()

NameError: name 'sys' is not defined

In [ ]:
range1 = df[(df["timestamp"]>="2025-07-16")&(df["timestamp"]<="2025-08-25")]
range2 = df[(df["timestamp"]>="2025-08-04")&(df["timestamp"]<="2025-09-22")]
print(range1["timestamp"].dt.date.value_counts().sort_index())
print(range2["timestamp"].dt.date.value_counts().sort_index())

In [ ]:
range1["name"].value_counts().sort_index()

In [ ]:
range1.groupby("date")["name"].value_counts().sort_index()

In [ ]:
range2["name"].value_counts().sort_index()

In [ ]:
range2.groupby("date")["name"].value_counts().sort_index()

# Get Node sizes

In [ ]:
node_names1 = range1.groupby(by=["name","account","date"])["node_name"].value_counts().sort_index().reset_index()
node_names1

In [ ]:
node_names2 = range2.groupby(by=["name","account","date"])["node_name"].value_counts().sort_index().reset_index()
node_names2

In [ ]:
node_names = pd.merge(node_names1,node_names2, how="outer", on=["name","account","date","node_name"], suffixes=["_1","_2"])
node_names = node_names.sort_values(by=["name","account","date"])
node_names

# Node SIzes for Targeting

In [ ]:
targeting1 = range1[range1["name"]=="k8-targeting"].groupby(by=["account","audience_id","targeting_outlook","date"])["node_name"].nunique().reset_index().rename(columns={"node_name":"count"})
targeting1_names = range1[range1["name"]=="k8-targeting"].groupby(by=["account","audience_id","targeting_outlook","date"])["node_name"].unique().reset_index()
targeting1 = pd.merge(targeting1,targeting1_names, how="outer", on=["account","audience_id","targeting_outlook","date"]).sort_values(by=["account","audience_id","date"]).reset_index()
targeting1

In [ ]:
targeting2 = range2[range2["name"]=="k8-targeting"].groupby(by=["account","audience_id","targeting_outlook","date"])["node_name"].nunique().reset_index().rename(columns={"node_name":"count"})
targeting2_names = range2[range2["name"]=="k8-targeting"].groupby(by=["account","audience_id","targeting_outlook","date"])["node_name"].unique().reset_index()
targeting2 = pd.merge(targeting2,targeting2_names, how="outer", on=["account","audience_id","targeting_outlook","date"]).sort_values(by=["account","audience_id","date"]).reset_index()
targeting2

In [ ]:
targeting = pd.merge(targeting1,targeting2, how="outer", on=["account","audience_id","targeting_outlook","date"],suffixes=("_1","_2"))
targeting[targeting["audience_id"].isin(targeting[targeting["date"].astype("string")=="2025-08-07"]["audience_id"].unique().tolist())]

In [ ]:
targeting["same"] = targeting[["node_name_1","node_name_2"]].apply(lambda x: (x[0] == x[1]).all(), axis=1)
targeting

In [ ]:
targeting

In [ ]:
from datetime import datetime
temp = targeting[targeting["same"] == False].dropna(subset=["count_1"])
temp = temp.dropna(subset=["count_2"])
temp.to_csv(f"DataChecks/prefect_logs/check_prefect_logs_{datetime.today()}.csv")
temp